zeebe:
  broker:
    exporters:
      mongo:
        # Mongo Exporter ----------
        # An example configuration for the mongo exporter:
        #

        className: com.demo.zeebemongoexporter.MongoExporter
        jarPath: /usr/local/zeebe/lib/mongodb-exporter-0.0.1-SNAPSHOT.jar

        args:
          url: http://localhost:27017/
          dbName: zeebe

          bulk:
            delay: 5
            size: 1000
          col:
            prefix: zeebe-record
            createCollections: true
            command: false
            event: true
            rejection: false
            deployment: true
            error: true
            incident: true
            job: true
            jobBatch: false
            message: true
            messageSubscription: true
            variable: true
            variableDocument: true
            workflowInstance: true
            workflowInstanceCreation: false
            workflowInstanceSubscription: false
            timers: true

